# Generated by Django 4.0.4 on 2022-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filter',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('qtype', models.CharField(default='all', max_length=50)),
                ('ctype', models.CharField(default='all', max_length=50)),
                ('vessel', models.TextField(default='all')),
                ('hardrestype', models.CharField(default='all', max_length=50)),
                ('humanrestype', models.CharField(default='all', max_length=50)),
                ('procrestype', models.CharField(default='all', max_length=50)),
                ('roviqlst', models.TextField(default='all')),
            ],
        ),
    ]
