# Generated by Django 4.0.4 on 2022-06-16 19:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gapAnalysis',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('uid_json', jsonfield.fields.JSONField()),
            ],
        ),
    ]
