# Generated by Django 4.0.4 on 2022-06-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_filter_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='saved',
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='saved',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
